ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.doduohor.MainKt.module
    ]
  }
}

security {
    basic {
      username = "admin"
      username = ${?BASIC_AUTH_USERNAME}

      password = "admin"
      password = ${?BASIC_AUTH_PASSWORD}
    }
}

database {
    enabled = true
    url = "jdbc:postgresql://localhost:5432/sports_facility_booking"
    url = ${?DATABASE_URL}
    user = "sports"
    user = ${?DATABASE_USER}
    password = "sports"
    password = ${?DATABASE_PASSWORD}
}

mongo{
    host = "mongo"
    host = ${?MONGO_HOST}

    port = 27017
    port = ${?MONGO_PORT}

    username = "mongo_admin"
    username = ${?MONGO_USERNAME}

    password = "mongo_admin"
    password = ${?MONGO_PASSWORD}

    database = "sports_facility_booking"
    database = ${?MONGO_DATABASE}
}

rabbitmq {
    host = "localhost"
    host = ${?RABBIT_HOST}

    port = 5672
    port = ${?RABBIT_PORT}

    username = "guest"
    username = ${?RABBIT_USER}

    password = "guest"
    password = ${?RABBIT_PASSWORD}

    exchange = "sports.events"
    queue = "sports.measurements"
    routingKey = "measurement.created"
    exchange = ${?RABBIT_EXCHANGE}
    queue = ${?RABBIT_QUEUE}
    routingKey = ${?RABBIT_ROUTING_KEY}

    deadLetterExchange = "sports.events.dlq"
    deadLetterExchange = ${?RABBIT_EXCHANGE_DLQ}

    deadLetterQueue = "sports.measurements.dlq"
    deadLetterQueue = ${?RABBIT_QUEUE_DLQ}

    deadLetterRoutingKey = "measurement.created.dlq"
    deadLetterRoutingKey = ${?RABBIT_ROUTING_KEY_DLQ}
}

telegram {
    bot_token = ${?TELEGRAM_BOT_TOKEN}
    chat_id = ${?TELEGRAM_CHAT_ID}
}
