ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.doduohor.MainKt.module
    ]
  }
}

security {
    basic {
      username = "admin"
      username = ${?BASIC_AUTH_USERNAME}

      password = "admin"
      password = ${?BASIC_AUTH_PASSWORD}
    }
}

database {
  enabled = true
  url = "jdbc:postgresql://localhost:5432/sports_facility_booking"
  url = ${?DATABASE_URL}
  user = "sports"
  user = ${?DATABASE_USER}
  password = "sports"
  password = ${?DATABASE_PASSWORD}
}
