ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.doduohor.SerializationKt.configureSerialization
      com.doduohor.StatusPagesKt.configureStatusPages
      com.doduohor.RoutingKt.configureRouting
    ]
  }
}